### ISSUE TITLE
Container crash "Unable to verify OIDC token oidc: expected audience..."

### ISSUE THREAD

**Issue by patricknelson** [salrashid123/gce_metadata_server#6]
I have two separate Cloud Run instances that I'm testing (not at exactly the same time per se). When I start up the metadata server container for the first time, I'm able to fetch an OAuth token (to [authenticate service-to-service](https://cloud.google.com/run/docs/authenticating/service-to-service#nodejs)). But when I issue a new request with a different `audience` the `apogiatzis/livereloading` container crashes. 

For example, I have two cloud run URL's  (anonymizing for proprietary reasons):

- https://app1-abcde12345.a.run.app
- https://app2-vwxyz98765.a.run.app

## Steps to reproduce

In `docker-compose.yml` I've defined:

```yml
version: '3'
services:
  proxy:
    build: nginx:mainline
    restart: always

  metadata.google.internal:
    image: salrashid123/gcemetadataserver
    container_name: metadata
    command: "-port :80
              --serviceAccountFile /conf/sa.json
              --tokenScopes https://www.googleapis.com/auth/cloud-platform
             "
    volumes:
      - .secret/:/conf/
```

In one window, run both containers, i.e. `docker-compose up` then in a new window,  SSH into the `proxy` container via `docker-compose exec proxy bash` this is what happens:

```bash
root@301894f65b61:/# curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://app1-abcde12345.a.run.app
[LONG KEY OUTPUT HERE]

root@301894f65b61:/# curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://app2-vwxyz98765.a.run.app
curl: (52) Empty reply from server
```

Error output in the main `docker-compose up` window:

```
2020/06/18 03:39:48 salrashid123/oauth2/google: Unable to verify OIDC token oidc: expected audience "https://app1-abcde12345.a.run.app" got ["https://app2-vwxyz98765.a.run.app"]
```
